// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GreetService 提供一个简单的问候方法，作为 Wails 绑定的示例服务。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Greet 返回针对 name 的问候语。
 */
export function Greet(name: string): $CancellablePromise<string> {
    return $Call.ByID(794126130, name);
}
