// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * QRService 提供二维码生成能力，作为 Wails 绑定的示例服务。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Generate 根据文本生成 PNG 格式的二维码。
 */
export function Generate(text: string, size: number): $CancellablePromise<string | null> {
    return $Call.ByID(2540283258, text, size);
}
